name: yhcjb
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: JohnWall2016 <email@example.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  path: ^1.4.1
  mysql1: ^0.17.0
  xlsx_decoder:
    path: ../xlsx_decoder
  args: ^1.4.0
  intl: ^0.15.8

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  args:
    path: ../args